// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AppClient.Models;
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace AppClient.Models;

public partial class ChatGroup
{
    public int ID { get; set; }

    public int? ID_Chat { get; set; }

    public int? ID_Group { get; set; }

    public virtual Chat ID_ChatNavigation { get; set; }

    public virtual Group ID_GroupNavigation { get; set; }
}