// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppClient.Models;

public partial class Chat
{
    public int ID { get; set; }

    public string Name { get; set; }

    public int ID_User_CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ID_ChatType { get; set; }

    public string ChatTopic { get; set; }

    public virtual ICollection<ChatGroup> ChatGroups { get; set; } = new List<ChatGroup>();

    public virtual ICollection<ChatMember> ChatMembers { get; set; } = new List<ChatMember>();

    public virtual ChatType ID_ChatTypeNavigation { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}