// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AppClient.Models;
using System;
using System.Collections.Generic;

namespace AppClient.Models;

public partial class ChatMember
{
    public int ID { get; set; }

    public int? ID_Userr { get; set; }

    public int? ID_Chat { get; set; }

    public int? ID_ChatRole { get; set; }

    public DateTime? DateJoining { get; set; }

    public virtual Chat ID_ChatNavigation { get; set; }

    public virtual ChatRole ID_ChatRoleNavigation { get; set; }

    public virtual Userr ID_UserrNavigation { get; set; }
}