// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.VisualBasic.FileIO;
using System;
using System.Collections.Generic;

namespace AppClient.Models;

public partial class Files
{
    public int ID { get; set; }

    public string FileName { get; set; }

    public byte[] FileDate { get; set; }

    public int? ID_Messages { get; set; }

    public int? ID_FileType { get; set; }
    public string Url { get; set; }

    public virtual FileType ID_FileTypeNavigation { get; set; }

    public virtual Message ID_MessagesNavigation { get; set; }
}