// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppClient.Models;

public partial class FileType
{
    public int ID { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Files> Files { get; set; } = new List<Files>();
}