// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppClient.Models;

public partial class Group
{
    public int ID { get; set; }

    public string Name { get; set; }

    public virtual ICollection<ChatGroup> ChatGroups { get; set; } = new List<ChatGroup>();
}