// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using AppClient.Models;
using System;
using System.Collections.Generic;

namespace AppClient.Models;

public partial class Message
{
    public int ID { get; set; }

    public string ContentMessages { get; set; }

    public DateTime? Timestamp { get; set; }

    public int? ID_User { get; set; }

    public int? ID_Chat { get; set; }

    public virtual ICollection<Files> Files { get; set; } = new List<Files>();

    public virtual Chat ID_ChatNavigation { get; set; }

    public virtual Userr ID_UserNavigation { get; set; }
}