// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AppServerTest.Models;

public partial class MessageServerContext : DbContext
{
    public MessageServerContext()
    {
    }

    public MessageServerContext(DbContextOptions<MessageServerContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Chat> Chats { get; set; }

    public virtual DbSet<ChatGroup> ChatGroups { get; set; }

    public virtual DbSet<ChatMember> ChatMembers { get; set; }

    public virtual DbSet<ChatRole> ChatRoles { get; set; }

    public virtual DbSet<ChatType> ChatTypes { get; set; }

    public virtual DbSet<Files> Files { get; set; }

    public virtual DbSet<FileType> FileTypes { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<Userr> Userrs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=212.12.19.253;Initial Catalog=MessageServer;User ID=KirillinaAlina;Password=lEBP$o/b~31*Xk[;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Chat>(entity =>
        {
            entity.ToTable("Chat");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Name).HasMaxLength(50);

            entity.HasOne(d => d.ID_ChatTypeNavigation).WithMany(p => p.Chats)
                .HasForeignKey(d => d.ID_ChatType)
                .HasConstraintName("FK_Chat_ChatType");
        });

        modelBuilder.Entity<ChatGroup>(entity =>
        {
            entity.ToTable("ChatGroup");

            entity.HasOne(d => d.ID_ChatNavigation).WithMany(p => p.ChatGroups)
                .HasForeignKey(d => d.ID_Chat)
                .HasConstraintName("FK_ChatGroup_Chat");

            entity.HasOne(d => d.ID_GroupNavigation).WithMany(p => p.ChatGroups)
                .HasForeignKey(d => d.ID_Group)
                .HasConstraintName("FK_ChatGroup_Group");
        });

        modelBuilder.Entity<ChatMember>(entity =>
        {
            entity.Property(e => e.DateJoining).HasColumnType("datetime");

            entity.HasOne(d => d.ID_ChatNavigation).WithMany(p => p.ChatMembers)
                .HasForeignKey(d => d.ID_Chat)
                .HasConstraintName("FK_ChatMembers_Chat");

            entity.HasOne(d => d.ID_ChatRoleNavigation).WithMany(p => p.ChatMembers)
                .HasForeignKey(d => d.ID_ChatRole)
                .HasConstraintName("FK_ChatMembers_ChatRole");

            entity.HasOne(d => d.ID_UserrNavigation).WithMany(p => p.ChatMembers)
                .HasForeignKey(d => d.ID_Userr)
                .HasConstraintName("FK_ChatMembers_Userr");
        });

        modelBuilder.Entity<ChatRole>(entity =>
        {
            entity.ToTable("ChatRole");

            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<ChatType>(entity =>
        {
            entity.ToTable("ChatType");

            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Files>(entity =>
        {
            entity.Property(e => e.FileDate)
                .HasMaxLength(50)
                .IsFixedLength();

            entity.HasOne(d => d.ID_FileTypeNavigation).WithMany(p => p.Files)
                .HasForeignKey(d => d.ID_FileType)
                .HasConstraintName("FK_Files_FileType");

            entity.HasOne(d => d.ID_MessagesNavigation).WithMany(p => p.Files)
                .HasForeignKey(d => d.ID_Messages)
                .HasConstraintName("FK_Files_Messages");
        });

        modelBuilder.Entity<FileType>(entity =>
        {
            entity.ToTable("FileType");

            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_ChatGroups");

            entity.ToTable("Group");

            entity.Property(e => e.Name)
                .HasMaxLength(10)
                .IsFixedLength();
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.Property(e => e.ContentMessages)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Timestamp).HasColumnType("datetime");

            entity.HasOne(d => d.ID_ChatNavigation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ID_Chat)
                .HasConstraintName("FK_Messages_Chat");

            entity.HasOne(d => d.ID_UserNavigation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ID_User)
                .HasConstraintName("FK_Messages_Userr");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.ToTable("Role");

            entity.Property(e => e.Name).HasMaxLength(50);
        });

        modelBuilder.Entity<Userr>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_Users");

            entity.ToTable("Userr");

            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.Login)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}