// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AppClient.Models;

public partial class Userr
{
    public int ID { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public int? Phone { get; set; }

    [Column(TypeName = "date")] // Указываем тип DATE для SQL Server
    public DateTime BirthDate { get; set; } // Хранится как дата без времени

    public string AvatarUrl { get; set; }
    public bool IsActive { get; set; }

    public virtual ICollection<ChatMember> ChatMembers { get; set; } = new List<ChatMember>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}